version: '3.7'

services:
  scorp:
    build: .
    container_name: backendscorp
    command: sh entrypoint.prod.sh
    volumes:
      - .:/usr/src/app/
    expose:
      - 8000
    ports:
      - 9011:8000
    env_file:
      - .env
    depends_on:
      - scorpdbd

  scorpdbd:
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
        - 54320:5432
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - .env.db

  nginxscorp:
    image: library/nginx:latest
    ports:  # host-port 8011 (:) container-port 80
      - "8011:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media

