version: '3.7'

services:
  svitlotv:
    build: .
    container_name: backendsvitlotv
    command: sh entrypoint.prod.sh
    volumes:
      - .:/usr/src/app/
    expose:
      - 8000
    ports:
      - 4000:8000
    env_file:
      - .env
    depends_on:
      - svitlodbd

  svitlodbd:
    image: postgres
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - .env.db

  nginxsvitlotv:
    image: library/nginx:latest
    ports:  # host-port 8111 (:) container-port 80
      - "8111:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media

