# Generated by Django 5.0.4 on 2024-05-29 21:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.TextField(blank=True, max_length=100)),
                ('genre', models.TextField(blank=True, max_length=100)),
                ('audience', models.TextField(blank=True, max_length=100)),
                ('running_time', models.TextField(blank=True, max_length=100)),
                ('format', models.TextField(blank=True, max_length=100)),
                ('technique', models.TextField(blank=True, max_length=100)),
                ('sound', models.TextField(blank=True, max_length=100)),
                ('languages', models.TextField(blank=True, max_length=100)),
                ('producers', models.TextField(blank=True, max_length=100)),
                ('director', models.TextField(blank=True, max_length=100)),
                ('screenplay', models.TextField(blank=True, max_length=100)),
                ('short_text', models.TextField(blank=True, max_length=6500)),
                ('big_text', wagtail.fields.RichTextField(blank=True, max_length=62000)),
                ('big_picture', models.ForeignKey(blank=True, help_text='project top image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('slider_image', models.ForeignKey(blank=True, help_text='project image for slider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
