# Generated by Django 5.0.4 on 2024-05-28 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='running_time',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='slider_image',
            field=models.ForeignKey(blank=True, help_text='project image for slider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
