# Generated by Django 5.0.4 on 2024-06-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_newslist_left_picture_newslist_right_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslist',
            name='posts_per_page',
            field=models.IntegerField(default=4),
        ),
    ]
