# Generated by Django 5.0.4 on 2024-06-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectcategory_projectgenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.DeleteModel(
            name='ProjectGenre',
        ),
    ]
