# Generated by Django 5.0.4 on 2024-06-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='genres',
            field=models.ManyToManyField(blank=True, to='projects.genre'),
        ),
    ]
