# Generated by Django 5.0.4 on 2024-10-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_genre_name_en_genre_name_uk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='audience',
            field=models.TextField(blank=True, max_length=100, verbose_name='audience'),
        ),
        migrations.AlterField(
            model_name='project',
            name='director',
            field=models.TextField(blank=True, max_length=100, verbose_name='director'),
        ),
        migrations.AlterField(
            model_name='project',
            name='format',
            field=models.TextField(blank=True, max_length=100, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.TextField(blank=True, max_length=100, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='project',
            name='producers',
            field=models.TextField(blank=True, max_length=100, verbose_name='producers'),
        ),
        migrations.AlterField(
            model_name='project',
            name='running_time',
            field=models.TextField(blank=True, max_length=100, verbose_name='running time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenplay',
            field=models.TextField(blank=True, max_length=100, verbose_name='screenplay'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sound',
            field=models.TextField(blank=True, max_length=100, verbose_name='sound'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technique',
            field=models.TextField(blank=True, max_length=100, verbose_name='technique'),
        ),
    ]
