# Generated by Django 5.0.4 on 2024-10-21 00:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_audience_alter_project_director_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='big_picture',
            field=models.ForeignKey(blank=True, help_text='project top image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='project top image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='big_text',
            field=wagtail.fields.RichTextField(blank=True, max_length=62000, verbose_name='big text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.TextField(blank=True, max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='genre',
            field=models.TextField(blank=True, max_length=100, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='genres',
            field=models.ManyToManyField(blank=True, to='projects.genre', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_text',
            field=models.TextField(blank=True, max_length=6500, verbose_name='short text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slider_image',
            field=models.ForeignKey(blank=True, help_text='project image for slider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='project image for slider'),
        ),
    ]
