# Generated by Django 5.0.4 on 2024-06-02 22:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceartstoryproduction_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceartstoryproduction',
            name='body2',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Body 2'),
        ),
    ]
