# Generated by Django 5.0.4 on 2024-06-04 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ournews', '0003_alter_newsarticle_article_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 10, 10, 44, 461852)),
        ),
    ]
