# Generated by Django 5.0.4 on 2024-06-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ournews', '0004_alter_newsarticle_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='article_date',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='big_text',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='short_text',
        ),
    ]
