# Generated by Django 5.0.4 on 2024-06-04 10:27

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ournews', '0005_remove_newsarticle_article_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='big_text',
            field=wagtail.fields.RichTextField(blank=True, max_length=62000),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='short_text',
            field=models.TextField(blank=True, max_length=6500),
        ),
    ]
