# Generated by Django 5.0.4 on 2024-06-04 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ournews', '0006_newsarticle_big_text_newsarticle_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='news_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 4, 10, 31, 7, 334567), verbose_name='news date'),
            preserve_default=False,
        ),
    ]
