# Generated by Django 5.0.4 on 2024-06-05 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ournews', '0008_alter_newsarticle_short_text'),
        ('projects', '0004_newslist_posts_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='news_for_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='projects.project'),
        ),
    ]
