# Generated by Django 5.0.4 on 2024-05-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdatasettings',
            options={'verbose_name': 'Contact settings'},
        ),
        migrations.AlterModelOptions(
            name='socialmediasettings',
            options={'verbose_name': 'Social site settings'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name for about block'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='logotype',
            field=models.FileField(help_text='Upload logotype', max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='name',
            field=models.CharField(help_text='Social net name', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.URLField(help_text='URL to social network account'),
        ),
    ]
