# Generated by Django 5.0.4 on 2024-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactdata_post_addr2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
