# Generated by Django 5.0.4 on 2024-06-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='email_requests',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
