# Generated by Django 5.0.4 on 2024-05-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_services_homepage_services_background_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
