# Generated by Django 5.0.4 on 2024-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contactus_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name for contact us block'),
        ),
    ]
