# Generated by Django 5.0.4 on 2024-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_carrertitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='action_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
