# Generated by Django 5.0.4 on 2024-05-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_about_big_picture_ourteamcompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourteamcompany',
            old_name='genre',
            new_name='our_team',
        ),
    ]
