# Generated by Django 5.0.4 on 2024-06-06 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_career_action_text'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=230, verbose_name='Name')),
                ('last_name', models.CharField(max_length=230, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email address')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('country_residence', models.CharField(max_length=230, verbose_name='country of residence')),
                ('phone', models.CharField(max_length=230, verbose_name='phone')),
                ('nationality', models.CharField(max_length=230, verbose_name='nationality')),
                ('main_skill', models.CharField(max_length=230, verbose_name='main skill')),
                ('secondary_skill', models.CharField(max_length=230, verbose_name='secondary skill')),
                ('other_skill', models.CharField(max_length=230, verbose_name='other skill')),
                ('software', models.CharField(max_length=230, verbose_name='software')),
                ('availability', models.CharField(max_length=230, verbose_name='availability')),
                ('linkedin', models.CharField(max_length=230, verbose_name='linkedin')),
                ('website_reel', models.CharField(max_length=230, verbose_name='website reel')),
                ('message_about', models.TextField(verbose_name='message about')),
            ],
        ),
        migrations.CreateModel(
            name='CareerJoin',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('big_picture', models.ForeignKey(blank=True, help_text='Page top image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
