# Generated by Django 5.0.4 on 2024-06-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_careercontact_careerjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerjoin',
            name='action_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
