# Generated by Django 5.0.4 on 2024-06-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_carrertitles_careertitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='telegram_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='viber_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
