# Generated by Django 5.0.4 on 2024-06-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_career_redirect_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='button_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
