# Generated by Django 5.0.4 on 2024-07-22 12:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_career_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name for about block'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_text',
            field=wagtail.fields.RichTextField(default=0, verbose_name='About'),
            preserve_default=False,
        ),
    ]
