# Generated by Django 5.0.4 on 2024-10-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_about_about_name_about_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='button_get_in_touch_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_get_in_touch_title',
            field=models.CharField(default='GET IN TOUCH', max_length=255, verbose_name='GET IN TOUCH'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(default='Services', max_length=255, verbose_name='services title'),
        ),
    ]
