# Generated by Django 5.0.4 on 2024-10-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_homepage_for_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='careertitles',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='careertitles',
            name='name_uk',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
