# Generated by Django 5.0.4 on 2024-11-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_contactpage_for_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='last_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='last_name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='position_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='position_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
